runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: user
  CLOUD_SQL_PASSWORD: Hackaton
  CLOUD_SQL_DATABASE_NAME: product
  CLOUD_SQL_CONNECTION_NAME: lastminutecoders-ghack:us-central1:bdd-main
